// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: modules/pb/pb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Push request. Adds a number to aggregate Number to push
type PushReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num float32 `protobuf:"fixed32,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *PushReq) Reset() {
	*x = PushReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_pb_pb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReq) ProtoMessage() {}

func (x *PushReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_pb_pb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReq.ProtoReflect.Descriptor instead.
func (*PushReq) Descriptor() ([]byte, []int) {
	return file_modules_pb_pb_proto_rawDescGZIP(), []int{0}
}

func (x *PushReq) GetNum() float32 {
	if x != nil {
		return x.Num
	}
	return 0
}

// Empty message
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_pb_pb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_modules_pb_pb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_modules_pb_pb_proto_rawDescGZIP(), []int{1}
}

// Creates a stream of notifications when running average exceeds the threshold provided message
type GetAvgAlarmStreamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// When average of pushed numbers exceeds this threshold, a notification will be sent to the response stream
	Threshold float32 `protobuf:"fixed32,1,opt,name=threshold,proto3" json:"threshold,omitempty"`
}

func (x *GetAvgAlarmStreamReq) Reset() {
	*x = GetAvgAlarmStreamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_pb_pb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvgAlarmStreamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvgAlarmStreamReq) ProtoMessage() {}

func (x *GetAvgAlarmStreamReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_pb_pb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvgAlarmStreamReq.ProtoReflect.Descriptor instead.
func (*GetAvgAlarmStreamReq) Descriptor() ([]byte, []int) {
	return file_modules_pb_pb_proto_rawDescGZIP(), []int{2}
}

func (x *GetAvgAlarmStreamReq) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

// Notification message sent to the stream when average aggregate is greater than the threshold
type GetAvgAlarmStreamRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Current average value that was compared to the threshold
	Avg float32 `protobuf:"fixed32,1,opt,name=avg,proto3" json:"avg,omitempty"`
}

func (x *GetAvgAlarmStreamRes) Reset() {
	*x = GetAvgAlarmStreamRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_pb_pb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAvgAlarmStreamRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvgAlarmStreamRes) ProtoMessage() {}

func (x *GetAvgAlarmStreamRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_pb_pb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvgAlarmStreamRes.ProtoReflect.Descriptor instead.
func (*GetAvgAlarmStreamRes) Descriptor() ([]byte, []int) {
	return file_modules_pb_pb_proto_rawDescGZIP(), []int{3}
}

func (x *GetAvgAlarmStreamRes) GetAvg() float32 {
	if x != nil {
		return x.Avg
	}
	return 0
}

var File_modules_pb_pb_proto protoreflect.FileDescriptor

var file_modules_pb_pb_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x1b, 0x0a, 0x07, 0x50, 0x75, 0x73,
	0x68, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x34, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x68, 0x72, 0x65, 0x73,
	0x68, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x74, 0x68, 0x72, 0x65,
	0x73, 0x68, 0x6f, 0x6c, 0x64, 0x22, 0x28, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x41,
	0x6c, 0x61, 0x72, 0x6d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x76, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x61, 0x76, 0x67, 0x32,
	0x80, 0x01, 0x0a, 0x0f, 0x41, 0x76, 0x67, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x50, 0x75, 0x73, 0x68, 0x12, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x41,
	0x6c, 0x61, 0x72, 0x6d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x76, 0x67, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x76, 0x67,
	0x41, 0x6c, 0x61, 0x72, 0x6d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x14, 0x5a, 0x12, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x6f, 0x2f, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_pb_pb_proto_rawDescOnce sync.Once
	file_modules_pb_pb_proto_rawDescData = file_modules_pb_pb_proto_rawDesc
)

func file_modules_pb_pb_proto_rawDescGZIP() []byte {
	file_modules_pb_pb_proto_rawDescOnce.Do(func() {
		file_modules_pb_pb_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_pb_pb_proto_rawDescData)
	})
	return file_modules_pb_pb_proto_rawDescData
}

var file_modules_pb_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_modules_pb_pb_proto_goTypes = []interface{}{
	(*PushReq)(nil),              // 0: pb.PushReq
	(*Empty)(nil),                // 1: pb.Empty
	(*GetAvgAlarmStreamReq)(nil), // 2: pb.GetAvgAlarmStreamReq
	(*GetAvgAlarmStreamRes)(nil), // 3: pb.GetAvgAlarmStreamRes
}
var file_modules_pb_pb_proto_depIdxs = []int32{
	0, // 0: pb.AvgAlarmService.Push:input_type -> pb.PushReq
	2, // 1: pb.AvgAlarmService.GetAvgAlarmStream:input_type -> pb.GetAvgAlarmStreamReq
	1, // 2: pb.AvgAlarmService.Push:output_type -> pb.Empty
	3, // 3: pb.AvgAlarmService.GetAvgAlarmStream:output_type -> pb.GetAvgAlarmStreamRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_modules_pb_pb_proto_init() }
func file_modules_pb_pb_proto_init() {
	if File_modules_pb_pb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_pb_pb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_pb_pb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_pb_pb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvgAlarmStreamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_pb_pb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAvgAlarmStreamRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_pb_pb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_pb_pb_proto_goTypes,
		DependencyIndexes: file_modules_pb_pb_proto_depIdxs,
		MessageInfos:      file_modules_pb_pb_proto_msgTypes,
	}.Build()
	File_modules_pb_pb_proto = out.File
	file_modules_pb_pb_proto_rawDesc = nil
	file_modules_pb_pb_proto_goTypes = nil
	file_modules_pb_pb_proto_depIdxs = nil
}
